language: node_js
node_js:
  - node
  - lts/*
matrix:
  allow_failures:
    - node_js: node
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
